AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 3008
    Runtime: python3.6

Resources:
  master:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: master
      CodeUri: lambda_functions/master/
      Handler: handler.lambda_handler
      Policies:
      - Statement:
        - Sid: AttachedPolicy
          Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource: '*'
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /run
            Method: get

  from0To27Worker1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: from0To27Worker1
      CodeUri: lambda_functions/from0To27Worker1/
      Handler: worker.lambda_handler

  from0To27Worker2:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: from0To27Worker2
      CodeUri: lambda_functions/from0To27Worker2/
      Handler: worker.lambda_handler

  from0To27Worker3:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: from0To27Worker3
      CodeUri: lambda_functions/from0To27Worker3/
      Handler: worker.lambda_handler

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StartApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/run/"
#   HelloWorldFunction:
#     Description: "Hello World Lambda Function ARN"
#     Value: !GetAtt HelloWorldFunction.Arn
#   HelloWorldFunctionIamRole:
#     Description: "Implicit IAM Role created for Hello World function"
#     Value: !GetAtt HelloWorldFunctionRole.Arn
